### ISSUE TITLE
ArgumentException when right-clicking "Dependencies" (ASP.NET 5)

### ISSUE THREAD

**Issue by stimpy77** [stimpy77/FastKoala#36]
In VS 2015. A completely new ASP.NET 5 preview project. 
Simply right clicked on <projectName>/Dependencies in solution explorer.

Output window:

```
FastKoala: Error: Unhandled ArgumentException (System.ArgumentException):
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.IO.FileInfo.Init(String fileName, Boolean checkHost)
   at System.IO.FileInfo..ctor(String fileName)
   at Wijits.FastKoala.FastKoalaPackage.<EnableBuildTimeTransformationsMenuItem_BeforeQueryStatus>d__3f.MoveNext() in c:\projects\fastkoala\Fast Koala\FastKoalaPackage.cs:line 547
Please forward this log to jon@wijits.com
FastKoala: Error: Unhandled ArgumentException (System.ArgumentException):
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.IO.FileInfo.Init(String fileName, Boolean checkHost)
   at System.IO.FileInfo..ctor(String fileName)
   at Wijits.FastKoala.FastKoalaPackage.<AddMissingTransformationsMenuItem_BeforeQueryStatus>d__57.MoveNext() in c:\projects\fastkoala\Fast Koala\FastKoalaPackage.cs:line 667
Please forward this log to jon@wijits.com
FastKoala: [Your response: 'Yes'] .. Thanks
```

**Comment by stimpy77** [comment]
ASP.NET 5 isn't supported (at all) but Fast Koala should be more graceful about right-clicking stuff like that.
