### ISSUE TITLE
Projects in solution folders need to be supported

### ISSUE THREAD

**Issue by stimpy77** [stimpy77/FastKoala#38]
Fast Koala causes an exception to be thrown when the user has the project being manipilated in a solution folder. There needs to be solution tree traversal rather than root traversal when finding the project.

**Comment by stimpy77** [comment]
FYI if anyone's looking for a workaround, just temporarily move the project to the root of the solution tree, save the solution, apply Fast Koala's action, save all, then move the project back to its solution folder.

**Comment by bunceg** [comment]
Hi  first of all, thanks for this. Looks like it's going to be a great addition to our toolset. Do you know if this is going to be fixed soon? Thanks for the workaround btw!

I assume this is causing this error:

FastKoala: Error: Unhandled NullReferenceException (System.NullReferenceException):
   at Wijits.FastKoala.Utilities.ProjectUtilities.IsType(Project project, Guid projectType) in c:\projects\fastkoala\Fast Koala\Utilities\ProjectUtilities.cs:line 19
   at Wijits.FastKoala.Transformations.BuildTimeTransformationsEnabler.get_HasBuildTimeTransformationsEnabled() in c:\projects\fastkoala\Fast Koala\Transformations\BuildTimeTransformationsEnabler.cs:line 556
   at Wijits.FastKoala.Transformations.BuildTimeTransformationsEnabler.get_HasMissingTransforms() in c:\projects\fastkoala\Fast Koala\Transformations\BuildTimeTransformationsEnabler.cs:line 598
   at Wijits.FastKoala.FastKoalaPackage.<AddMissingTransformationsMenuItem_BeforeQueryStatus>d__54.MoveNext() in c:\projects\fastkoala\Fast Koala\FastKoalaPackage.cs:line 768
Please forward this log to jon@wijits.com
FastKoala: [Your response: 'Yes'] .. Thanks

**Comment by stimpy77** [comment]
Sorry, I can't promise anything, but might have time this weekend to address this.

**Comment by bunceg** [comment]
ok, thanks for the quick reply

**Comment by stimpy77** [comment]
Reproduced and resolved.
